// GENERATED by `python -m packages.contracts.export`. Do not edit by hand.
//
// These types come from the Pydantic models in packages/contracts/models.py.
// One source of truth for the API and the cockpit.
//
// Money and dates are `string` on the wire on purpose -- a Decimal serialized as a
// JSON float is exactly the drift we are avoiding. Format them, never sum them.

export type Actor = "devin" | "calle" | "system" | "human"
export type Answer = "yes" | "no" | "unknown"
export type AuditStatus = "audited" | "audit_expired" | "never_audited"
export type Channel = "voice" | "email" | "marketplace"
export type Criticality = "low" | "medium" | "high" | "critical"
export type Currency = "EUR" | "USD" | "GBP" | "unknown"
export type DecisionStatus = "ready" | "approved"
export type FreightMode = "air" | "sea" | "road"
export type Level = "info" | "warn" | "error"
export type OutreachStatus = "pending" | "in_progress" | "completed" | "failed"
export type PartClass = "rolling_bearing" | "fastener" | "seal" | "electronic_component"
export type PolicyRule = "blocked_origin_country" | "missing_required_certification" | "audit_required_and_not_audited" | "lead_time_after_line_stop"
export type Stage = "detected" | "researching" | "calling" | "costing" | "decided"
export type StockStatus = "free_in_stock" | "in_stock_allocated" | "to_be_made" | "unavailable" | "unclear"

export interface ApproveDecisionRequest {
  decision_revision: number
  approved_by: string
}

export interface Candidate {
  case_id: string
  supplier_ref: string
  supplier_name: string
  country: string
  confidence: number
  why_matched: string
  channel: Channel
  /** "erp" for an approved supplier, "web" for one researched online */
  source?: string
  compliance: ComplianceResult
}

/** Everything the case page needs, in one response. */
export interface CaseSnapshot {
  case_id: string
  stage: Stage
  incident: Incident
  part: Part
  profile_summary?: Record<string, unknown>
  candidates?: Candidate[]
  supplier_records?: SupplierRecord[]
  outreach_tasks?: OutreachTask[]
  claims?: Claim[]
  decision?: Decision | null
  devin_session_url?: string | null
  last_event_seq?: number
}

export interface CaseSummary {
  case_id: string
  part_id: string
  item_name: string
  stage: Stage
  qty_required: number
  line_stop_at: string
  opened_at: string
  pr_url?: string | null
}

/** A Quote, plus what the call could and could not establish. */
export interface Claim {
  task_id: string
  case_id: string
  supplier_ref: string
  available?: boolean
  qty_offered?: number
  unit_price?: string | null
  price_breaks?: PriceBreak[]
  currency?: Currency
  moq?: number | null
  lead_time_days?: number | null
  expedite_option?: ExpediteOption | null
  incoterm?: string | null
  certs_claimed?: string[]
  payment_terms?: string | null
  notes?: string
  transcript?: TranscriptTurn[]
  summary?: string
  transcript_url?: string | null
  recording_url?: string | null
  confidence?: number
  raw?: unknown
  round?: number
  call_id?: string | null
  earliest_ready_text?: string
  stock_status?: StockStatus
  price_quoted?: Answer
  part_number_confirmed?: Answer
  certification_current?: Answer
  evidence?: string[]
  received_at?: string | null
}

/** The rules of the house. Every policy rule reads exactly one field here. */
export interface CompanyProfile {
  legal_entity: string
  country: string
  blocked_origin_countries?: string[]
  required_certifications?: Record<string, string[]>
  audit_required_above_criticality?: Criticality
  single_po_budget_eur: string
  requires_second_quote_above_eur: string
  /** Weighted average cost of capital, for carrying cost */
  wacc: number
  warehousing_eur_per_pallet_month: string
  pieces_per_pallet: number
  /** origin country -> ad valorem rate */
  duty_rates?: Record<string, number>
  freight_eur_per_kg?: Record<string, string>
  transit_days?: Record<string, number>
}

export interface ComplianceResult {
  passed: boolean
  failed_rules?: PolicyRule[]
  /** Rule -> one plain sentence. What the UI prints next to the rule name. */
  explanations?: Record<string, string>
}

export interface Decision {
  case_id: string
  strategies?: Strategy[]
  recommended_strategy_id?: string | null
  runner_up_ids?: string[]
  rationale_md?: string
  policy_report_url?: string | null
  cost_report_url?: string | null
  pr_url?: string | null
  devin_session_url?: string | null
  decided_at?: string | null
  revision?: number
  status?: DecisionStatus
  checks?: DecisionChecks
  approved_at?: string | null
  approved_by?: string | null
}

export interface DecisionChecks {
  policy_passed: boolean
  cost_model_passed: boolean
}

export interface Event {
  /** Monotonic within a case. The UI polls with ?since= */
  seq?: number
  case_id: string
  ts: string
  actor: Actor
  stage: Stage
  level?: Level
  message: string
  payload?: Record<string, unknown>
}

/** Pay `surcharge` total to pull delivery in by `days`. */
export interface ExpediteOption {
  days: number
  surcharge: string
}

/** A shortage, as our own records see it. Claims are not involved yet. */
export interface Incident {
  case_id: string
  part_id: string
  plant_id: string
  production_line: string
  qty_required: number
  qty_on_hand: number
  needed_by: string
  line_stop_at: string
  line_stop_cost_per_hour: string
  currency?: Currency
  incumbent_supplier_id?: string | null
  reason?: string
  plants?: IncidentPlant[]
}

export interface IncidentPlant {
  plant_id: string
  name: string
  production_line: string
}

/** A row on the inventory screen: one part, and whether it can be triggered. */
export interface InventoryRow {
  part_id: string
  item_code: string
  item_name: string
  part_class: string
  criticality: string
  plant_id: string
  on_hand: number
  reorder_level: number
  daily_consumption: number
  days_of_cover: number | null
  below_reorder: boolean
  delayed_po: string | null
  suppliers: number
  open_case_id: string | null
}

export interface LandedCost {
  supplier_ref: string
  qty: number
  mode: FreightMode
  goods_cost: string
  freight: string
  duty: string
  tooling?: string
  carrying_cost: string
  expedite_surcharge: string
  total: string
  unit_effective: string
  breakdown_md?: string
}

export interface OpenCaseRequest {
  part_id: string
  qty_required?: number | null
  needed_by?: string | null
  case_id?: string | null
}

export interface OpenCaseResponse {
  case_id: string
  incident: Incident
  session_id: string
  session_url: string
  stubbed: boolean
  session_error?: string | null
}

export interface OpenPurchaseOrder {
  po_id: string
  part_id: string
  supplier_id: string
  qty: number
  promised_date: string
  /** Set when the supplier slips. The delay that fires the detector. */
  revised_date?: string | null
  status?: string
}

/** PR 22 TypeScript compatibility name for an opened Case response. */
export interface OpenedCase {
  case_id: string
  incident: Incident
  session_id: string
  session_url: string
  stubbed: boolean
  session_error?: string | null
}

export interface OrderLine {
  supplier_ref: string
  supplier_name: string
  qty: number
  mode: FreightMode
  eta: string
  landed: LandedCost
}

export interface OutreachBrief {
  part_spec: string
  qty: number
  needed_by: string
  target_price?: string | null
  floor_price?: string | null
  must_ask?: string[]
}

export interface OutreachTask {
  task_id: string
  case_id: string
  supplier_ref: string
  channel: Channel
  brief: OutreachBrief
  round?: number
  status?: OutreachStatus
  started_at?: string | null
  completed_at?: string | null
}

export interface Part {
  part_id: string
  /** ERPNext `item_code` */
  item_code: string
  item_name: string
  description: string
  /** Free-form technical spec, e.g. bore/OD/width/seal */
  spec?: Record<string, string>
  stock_uom?: string
  criticality?: Criticality
  part_class: PartClass
  /** Per piece. Drives freight cost. */
  weight_kg: number
  /** Customs tariff code. Drives duty by origin. */
  hs_code: string
  standard_cost: string
}

/** Buy at least `min_qty` and each unit costs `unit_price`. */
export interface PriceBreak {
  min_qty: number
  unit_price: string
}

export interface PublicCaseSnapshot {
  case_id: string
  stage: Stage
  incident: Incident
  part: Part
  profile_summary: PublicProfileSummary
  candidates?: Candidate[]
  supplier_records?: PublicSupplierRecord[]
  outreach_tasks?: OutreachTask[]
  claims?: PublicClaim[]
  decision?: PublicDecision | null
  devin_session_url?: string | null
  last_event_seq?: number
}

export interface PublicCaseSummary {
  case_id: string
  part_id: string
  item_name: string
  stage: Stage
  qty_required: number
  line_stop_at: string
  opened_at: string
}

export interface PublicClaim {
  task_id: string
  case_id: string
  supplier_ref: string
  available?: boolean
  qty_offered?: number
  unit_price?: string | null
  price_breaks?: PriceBreak[]
  currency?: Currency
  moq?: number | null
  lead_time_days?: number | null
  expedite_option?: ExpediteOption | null
  incoterm?: string | null
  certs_claimed?: string[]
  payment_terms?: string | null
  transcript?: TranscriptTurn[]
  summary?: string
  confidence?: number
  round?: number
  earliest_ready_text?: string
  stock_status?: StockStatus
  price_quoted?: Answer
  part_number_confirmed?: Answer
  certification_current?: Answer
  evidence?: string[]
  received_at?: string | null
}

export interface PublicDecision {
  case_id: string
  strategies?: Strategy[]
  recommended_strategy_id?: string | null
  runner_up_ids?: string[]
  rationale_md?: string
  policy_report_url?: string | null
  cost_report_url?: string | null
  devin_session_url?: string | null
  decided_at?: string | null
  revision: number
  status: DecisionStatus
  checks: DecisionChecks
  approved_at?: string | null
  approved_by?: string | null
}

export interface PublicEvent {
  seq?: number
  case_id: string
  ts: string
  actor: Actor
  stage: Stage
  level?: Level
  message: string
  payload?: Record<string, unknown>
}

export interface PublicProfileSummary {
  company_name: string
  home_country: string
  target_currency: Currency
  policy_labels?: string[]
  sourcing_constraints?: string[]
}

export interface PublicSupplierRecord {
  supplier_id: string
  supplier_name: string
  country: string
  locale?: string
  phone_masked: string
  channels?: Channel[]
  part_ids?: string[]
  approved?: boolean
  preferred?: boolean
  incumbent?: boolean
  contract_unit_price?: string | null
  standard_lead_days?: number | null
  certifications?: string[]
  certification_expires_at?: string | null
  audit_status?: AuditStatus
  known_allocations?: number
  max_historical_fill?: number
  price_breaks?: PriceBreak[]
}

/** What one supplier said. Every judgement field may be unknown. */
export interface Quote {
  task_id: string
  case_id: string
  supplier_ref: string
  available?: boolean
  qty_offered?: number
  unit_price?: string | null
  price_breaks?: PriceBreak[]
  currency?: Currency
  moq?: number | null
  lead_time_days?: number | null
  expedite_option?: ExpediteOption | null
  incoterm?: string | null
  certs_claimed?: string[]
  payment_terms?: string | null
  notes?: string
  transcript?: TranscriptTurn[]
  summary?: string
  transcript_url?: string | null
  recording_url?: string | null
  confidence?: number
  raw?: unknown
}

/** One row on the shortage dashboard. */
export interface ShortageAlert {
  part_id: string
  item_code: string
  item_name: string
  plant_id: string
  qty_on_hand: number
  reorder_level: number
  qty_required: number
  days_to_line_stop: number
  line_stop_at: string
  line_stop_cost_per_hour: string
  criticality: Criticality
  /** Set once a sourcing case exists for it */
  case_id?: string | null
  delayed_po_id?: string | null
}

/** ERPNext `Bin`: what is physically in a warehouse right now. */
export interface StockLevel {
  part_id: string
  warehouse: string
  plant_id: string
  actual_qty: number
  reserved_qty?: number
  reorder_level: number
  /** Line take rate, used to date the line stop */
  daily_consumption: number
}

export interface Strategy {
  strategy_id: string
  /** Human name, e.g. "Split: fast bridge + cheap bulk" */
  label: string
  lines: OrderLine[]
  total_cost: string
  unit_effective: string
  /** When the full quantity is on site */
  coverage_date: string
  meets_line_stop: boolean
  risk_score: number
  rationale?: string
}

/** Historical price paid, from our own purchase history. */
export interface SupplierPriceRecord {
  supplier_id: string
  part_id: string
  as_of: string
  unit_price: string
  qty: number
  currency?: Currency
}

/** What our files say about a supplier. The baseline a claim is checked against. */
export interface SupplierRecord {
  supplier_id: string
  /** ERPNext `supplier_name` */
  supplier_name: string
  /** ISO 3166-1 alpha-2 */
  country: string
  locale?: string
  /** Never the raw number. See contracts.phone. */
  phone_masked: string
  email?: string | null
  marketplace_url?: string | null
  channels?: Channel[]
  part_ids?: string[]
  approved?: boolean
  preferred?: boolean
  incumbent?: boolean
  contract_unit_price?: string | null
  /** Door-to-door days on the contracted mode, not ex-works */
  standard_lead_days?: number | null
  certifications?: string[]
  certification_expires_at?: string | null
  audit_status?: AuditStatus
  /** Units our records show already promised elsewhere */
  known_allocations?: number
  /** Largest order they have actually delivered for us */
  max_historical_fill?: number
  price_breaks?: PriceBreak[]
}

/** One thing said on the call, in order. */
export interface TranscriptTurn {
  offset_seconds?: number
  speaker?: string
  text?: string
}
