"""Export the frozen contract to its three consumers.

    python -m packages.contracts.export

Writes:
  apps/api/packages/contracts/schema.json        every model as JSON Schema
  apps/api/packages/contracts/claim.schema.json  Claim as JSON Schema
  apps/erp/lib/contracts.ts                       TypeScript types from the same models

The point of doing all three from one place: `Claim` is simultaneously our Python
type and the ERP client's TypeScript interface, generated together so contract
drift is not something anyone has to remember to avoid.

CALL-E is the exception. Its structured-result engine accepts only a small JSON
Schema subset -- no `anyOf`, no `$ref` -- and rejects what Pydantic emits, so the
call answer sheet is hand-written in `packages/contracts/schemas.py` and held to
these models by a test instead of by generation.
"""

from __future__ import annotations

import argparse
import json
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from pathlib import Path
from types import UnionType
from collections.abc import Mapping
from typing import Any, Union, get_args, get_origin

from pydantic import BaseModel

from packages.contracts import enums as contract_enums
from packages.contracts import models as contract_models
from packages.contracts.models import Contract

API_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = API_ROOT.parents[1]
SCHEMA_DIR = Path(__file__).resolve().parent
ERP_LIB = REPO_ROOT / "apps" / "erp" / "lib"

MODELS: dict[str, type[BaseModel]] = {
    name: obj
    for name, obj in vars(contract_models).items()
    if isinstance(obj, type)
    and issubclass(obj, BaseModel)
    and obj is not BaseModel
    and obj is not Contract
    and obj.__module__ == contract_models.__name__
}
# Enums live in two places now: Slice B's in enums.py, Slice C's (Channel,
# Currency) alongside Quote in models.py. Scan both so the generated TypeScript
# covers the whole contract.
ENUMS: dict[str, type[Enum]] = {
    name: obj
    for module in (contract_enums, contract_models)
    for name, obj in vars(module).items()
    if isinstance(obj, type)
    and issubclass(obj, Enum)
    and obj.__module__ == module.__name__
}


# ---------------------------------------------------------------------------
# TypeScript generation
# ---------------------------------------------------------------------------


def ts_type(annotation: Any) -> str:
    """Map a Python annotation to TypeScript.

    Money and dates deliberately become `string`: a Decimal serialized as a
    float in JSON is exactly the drift the money rule exists to prevent, so the
    wire format is a string and the UI formats it rather than doing arithmetic.
    """
    if annotation is Any:
        return "unknown"
    if annotation is type(None):
        return "null"
    # `Money` is Annotated[Decimal, ...]; unwrap to the type it decorates.
    if hasattr(annotation, "__metadata__"):
        return ts_type(annotation.__origin__)

    origin = get_origin(annotation)
    if origin in (Union, UnionType):
        parts = [ts_type(a) for a in get_args(annotation)]
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen)
    if origin in (list, set, tuple):
        args = get_args(annotation)
        return f"{ts_type(args[0])}[]" if args else "unknown[]"
    if origin is dict:
        args = get_args(annotation)
        key = "string" if not args else ("string" if args[0] in (str,) or (isinstance(args[0], type) and issubclass(args[0], Enum)) else "string")
        value = ts_type(args[1]) if len(args) > 1 else "unknown"
        return f"Record<{key}, {value}>"

    if isinstance(annotation, type):
        if issubclass(annotation, Enum):
            return annotation.__name__
        if issubclass(annotation, BaseModel):
            return annotation.__name__
        if annotation is Decimal:
            return "string"
        if annotation in (datetime, date):
            return "string"
        if annotation is bool:
            return "boolean"
        if annotation in (int, float):
            return "number"
        if annotation is str:
            return "string"
    return "unknown"


def generate_typescript() -> str:
    out: list[str] = [
        "// GENERATED by `python -m packages.contracts.export`. Do not edit by hand.",
        "//",
        "// These types come from the Pydantic models in packages/contracts/models.py.",
        "// One source of truth for the API and the cockpit.",
        "//",
        "// Money and dates are `string` on the wire on purpose -- a Decimal serialized as a",
        "// JSON float is exactly the drift we are avoiding. Format them, never sum them.",
        "",
    ]

    for name, enum_cls in sorted(ENUMS.items()):
        members = " | ".join(f'"{m.value}"' for m in enum_cls)
        out.append(f"export type {name} = {members}")
    out.append("")

    for name, model in sorted(MODELS.items()):
        doc = (model.__doc__ or "").strip().split("\n")[0]
        if doc:
            out.append(f"/** {doc} */")
        out.append(f"export interface {name} {{")
        for field_name, field in model.model_fields.items():
            optional = not field.is_required()
            rendered = ts_type(field.annotation)
            description = (field.description or "").strip()
            if description:
                out.append(f"  /** {description} */")
            out.append(f"  {field_name}{'?' if optional else ''}: {rendered}")
        out.append("}")
        out.append("")

    return "\n".join(out)


# ---------------------------------------------------------------------------


def artifact_contents() -> dict[Path, str]:
    """Render every generated artifact without touching the filesystem."""

    bundle = {name: model.model_json_schema() for name, model in sorted(MODELS.items())}
    return {
        SCHEMA_DIR / "schema.json": json.dumps(bundle, indent=2) + "\n",
        SCHEMA_DIR / "claim.schema.json": json.dumps(
            contract_models.Claim.model_json_schema(), indent=2
        )
        + "\n",
        ERP_LIB / "contracts.ts": generate_typescript().rstrip() + "\n",
    }


def stale_artifacts(artifacts: Mapping[Path, str] | None = None) -> list[Path]:
    """Return missing or stale generated paths without rewriting them."""

    expected = artifacts or artifact_contents()
    return [
        path
        for path, content in expected.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]


def write_artifacts(artifacts: Mapping[Path, str] | None = None) -> list[Path]:
    """Write the complete generated output set."""

    expected = artifacts or artifact_contents()
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return list(expected)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated artifacts do not match Pydantic",
    )
    args = parser.parse_args(argv)

    if args.check:
        stale = stale_artifacts()
        for path in stale:
            print(f"stale {path.relative_to(REPO_ROOT)}")
        return 1 if stale else 0

    for path in write_artifacts():
        print(f"generated {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
