"""Build the SQL system of record from the seeded YAML.

    python -m backend.record.seed_db

The YAML stays the human-editable source -- it diffs well and a teammate can
retune a price without writing SQL -- and this compiles it into
`backend/record/supplyguard.db`, which is what the API actually queries.

The database is a build artifact, not a source file: it is gitignored and
regenerated by `make db`, so there is no chance of the two drifting.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from backend.record.mock_erp import MockERP

DB_PATH = Path(__file__).parent / "supplyguard.db"
SCHEMA_PATH = Path(__file__).parent / "schema.sql"


def _text(value) -> str | None:
    """Money and dates go in as text, so nothing becomes a float on the way."""
    return None if value is None else str(value)


def _insert(conn: sqlite3.Connection, table: str, rows: list[tuple]) -> None:
    """INSERT with the placeholder count derived from the data, not hand-counted."""
    if not rows:
        return
    placeholders = ",".join("?" * len(rows[0]))
    conn.executemany(f"INSERT INTO {table} VALUES ({placeholders})", rows)


def build(db_path: Path | None = None, records: MockERP | None = None) -> Path:
    db_path = db_path or DB_PATH
    # Loading through MockERP means every row is validated against the contracts
    # and referentially checked before it reaches SQL.
    records = records or MockERP()

    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(SCHEMA_PATH.read_text(encoding="utf-8"))

        _insert(
            conn,
            "tabItem",
            [
                (
                    p.part_id, p.item_code, p.item_name, p.description,
                    json.dumps(p.spec), p.stock_uom, p.criticality.value,
                    p.part_class.value, p.weight_kg, p.hs_code, _text(p.standard_cost),
                )
                for p in records.list_parts()
            ],
        )

        _insert(
            conn,
            "tabWarehouse",
            [
                (
                    w["warehouse"], w["plant_id"], w["plant_name"],
                    w.get("city"), w.get("country"), json.dumps(w.get("production_lines", [])),
                )
                for w in records.warehouses
            ],
        )

        _insert(
            conn,
            "tabBin",
            [
                (
                    s.part_id, s.warehouse, s.plant_id, s.actual_qty,
                    s.reserved_qty, s.reorder_level, s.daily_consumption,
                )
                for s in records.list_stock()
            ],
        )

        for supplier in records.list_suppliers():
            _insert(conn, "tabSupplier", [
                (
                    supplier.supplier_id, supplier.supplier_name, supplier.country,
                    supplier.locale,
                    # The one place a raw number is written down. Everything that
                    # reads for an API response selects phone_masked instead.
                    records.raw_phone_for_outreach(supplier.supplier_id),
                    supplier.phone_masked,
                    supplier.email, supplier.marketplace_url,
                    json.dumps([c.value for c in supplier.channels]),
                    int(supplier.approved), int(supplier.preferred), int(supplier.incumbent),
                    _text(supplier.contract_unit_price), supplier.standard_lead_days,
                    json.dumps(supplier.certifications),
                    _text(supplier.certification_expires_at),
                    supplier.audit_status.value,
                    supplier.known_allocations, supplier.max_historical_fill,
                ),
            ])
            _insert(
                conn,
                "tabSupplierItem",
                [(supplier.supplier_id, part_id) for part_id in supplier.part_ids],
            )
            _insert(
                conn,
                "tabSupplierPriceBreak",
                [(supplier.supplier_id, b.min_qty, _text(b.unit_price)) for b in supplier.price_breaks],
            )

        _insert(
            conn,
            "tabItemPrice",
            [
                (r.supplier_id, r.part_id, _text(r.as_of), _text(r.unit_price), r.qty, r.currency)
                for part in records.list_parts()
                for r in records.get_price_history(part.part_id)
            ],
        )

        _insert(
            conn,
            "tabPurchaseOrder",
            [
                (po.po_id, po.part_id, po.supplier_id, po.qty,
                 _text(po.promised_date), _text(po.revised_date), po.status)
                for po in records.get_open_pos()
            ],
        )

        _insert(
            conn,
            "tabIncident",
            [
                (
                    i.case_id, i.part_id, i.plant_id, i.production_line,
                    i.qty_required, i.qty_on_hand, _text(i.needed_by),
                    i.line_stop_at.isoformat(), _text(i.line_stop_cost_per_hour),
                    i.currency, i.incumbent_supplier_id, i.reason,
                    json.dumps(
                        [plant.model_dump(mode="json") for plant in i.plants]
                    ),
                )
                for i in records.list_incidents()
            ],
        )

        for bom in records.boms:
            _insert(conn, "tabBOM", [
                (bom["bom_id"], bom["item_name"], bom["plant_id"], bom["production_line"]),
            ])
            _insert(
                conn,
                "tabBOMItem",
                [
                    (bom["bom_id"], i, line["part_id"], line["qty_per_unit"])
                    for i, line in enumerate(bom["lines"])
                ],
            )

        conn.execute(
            "INSERT INTO tabCompanyProfile VALUES (1, ?)",
            (records.get_company_profile().model_dump_json(),),
        )

        conn.commit()
    finally:
        conn.close()

    return db_path


def summarise(db_path: Path | None = None) -> list[tuple[str, int]]:
    conn = sqlite3.connect(db_path or DB_PATH)
    try:
        tables = [
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'tab%' ORDER BY name"
            )
        ]
        return [(t, conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]) for t in tables]
    finally:
        conn.close()


def main() -> None:
    path = build()
    print(f"built {path.relative_to(Path(__file__).resolve().parents[2])}  ({path.stat().st_size:,} bytes)")
    for table, count in summarise(path):
        print(f"  {table:<26} {count:>6,} rows")


if __name__ == "__main__":
    main()
