"""Export Python contracts to language-neutral and TypeScript projections.

    python -m packages.contracts.export

Writes:
  packages/contracts/schema.json      every model as JSON Schema
  packages/contracts/generated/contracts.ts

One checked-in generated module keeps the Python API, ERP, and SupplyOS on the
same domain and wire shapes. Provider-specific transport DTOs stay in the API.
"""

from __future__ import annotations

import json
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from pathlib import Path
from types import UnionType
from typing import Any, Union, get_args, get_origin

from pydantic import BaseModel

from packages.contracts import enums as contract_enums
from packages.contracts import models as contract_models
from packages.contracts.models import Contract

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = Path(__file__).resolve().parent
GENERATED_DIR = SCHEMA_DIR / "generated"

MODELS: dict[str, type[BaseModel]] = {
    name: obj
    for name, obj in vars(contract_models).items()
    if isinstance(obj, type)
    and issubclass(obj, BaseModel)
    and obj is not BaseModel
    and obj is not Contract
    and obj.__module__ == contract_models.__name__
}
# Enums live in `enums.py` and, for outreach, beside their models. Scan both so
# the generated TypeScript covers the whole contract.
ENUMS: dict[str, type[Enum]] = {
    name: obj
    for module in (contract_enums, contract_models)
    for name, obj in vars(module).items()
    if isinstance(obj, type)
    and issubclass(obj, Enum)
    and obj.__module__ == module.__name__
}


# ---------------------------------------------------------------------------
# TypeScript generation
# ---------------------------------------------------------------------------


def ts_type(annotation: Any) -> str:
    """Map a Python annotation to TypeScript.

    Money and dates deliberately become `string`: a Decimal serialized as a
    float in JSON is exactly the drift the money rule exists to prevent, so the
    wire format is a string and the UI formats it rather than doing arithmetic.
    """
    if annotation is Any:
        return "unknown"
    if annotation is type(None):
        return "null"
    # `Money` is Annotated[Decimal, ...]; unwrap to the type it decorates.
    if hasattr(annotation, "__metadata__"):
        return ts_type(annotation.__origin__)

    origin = get_origin(annotation)
    if origin in (Union, UnionType):
        parts = [ts_type(a) for a in get_args(annotation)]
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen)
    if origin in (list, set, tuple):
        args = get_args(annotation)
        return f"{ts_type(args[0])}[]" if args else "unknown[]"
    if origin is dict:
        args = get_args(annotation)
        key = "string" if not args else ("string" if args[0] in (str,) or (isinstance(args[0], type) and issubclass(args[0], Enum)) else "string")
        value = ts_type(args[1]) if len(args) > 1 else "unknown"
        return f"Record<{key}, {value}>"

    if isinstance(annotation, type):
        if issubclass(annotation, Enum):
            return annotation.__name__
        if issubclass(annotation, BaseModel):
            return annotation.__name__
        if annotation is Decimal:
            return "string"
        if annotation in (datetime, date):
            return "string"
        if annotation is bool:
            return "boolean"
        if annotation in (int, float):
            return "number"
        if annotation is str:
            return "string"
    return "unknown"


# Shapes of the launcher routes (apps/api/src/supplyos_api/routers/launch.py) rather than
# domain contracts, so there is no Pydantic model here to generate them from --
# but the cockpit needs them and a regenerate must not delete them again.
HANDWRITTEN_TS = """
/** A row on the inventory screen: one part, and whether it can be triggered. */
export interface InventoryRow {
  part_id: string
  item_code: string
  item_name: string
  part_class: string
  criticality: string
  plant_id: string
  on_hand: number
  reorder_level: number
  daily_consumption: number
  days_of_cover: number | null
  below_reorder: boolean
  delayed_po: string | null
  suppliers: number
  open_case_id: string | null
}

/** What opening a case returns: the case, and the Devin session working it. */
export interface OpenedCase {
  case_id: string
  incident: Incident
  session_id: string
  session_url: string
  stubbed: boolean
  session_error: string | null
}
"""


def generate_typescript() -> str:
    out: list[str] = [
        "// GENERATED by `python -m packages.contracts.export`. Do not edit by hand.",
        "//",
        "// These types come from the Pydantic models in packages/contracts/models.py,",
        "// and are shared by the API, ERP, and SupplyOS.",
        "//",
        "// Money and dates are `string` on the wire on purpose -- a Decimal serialized as a",
        "// JSON float is exactly the drift we are avoiding. Format them, never sum them.",
        "",
    ]

    for name, enum_cls in sorted(ENUMS.items()):
        members = " | ".join(f'"{m.value}"' for m in enum_cls)
        out.append(f"export type {name} = {members}")
    out.append("")

    for name, model in sorted(MODELS.items()):
        doc = (model.__doc__ or "").strip().split("\n")[0]
        if doc:
            out.append(f"/** {doc} */")
        out.append(f"export interface {name} {{")
        for field_name, field in model.model_fields.items():
            optional = not field.is_required()
            rendered = ts_type(field.annotation)
            description = (field.description or "").strip()
            if description:
                out.append(f"  /** {description} */")
            out.append(f"  {field_name}{'?' if optional else ''}: {rendered}")
        out.append("}")
        out.append("")

    out.append(HANDWRITTEN_TS.strip())
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------


def export_schemas() -> Path:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    bundle = {name: model.model_json_schema() for name, model in sorted(MODELS.items())}
    path = SCHEMA_DIR / "schema.json"
    path.write_text(json.dumps(bundle, indent=2) + "\n", encoding="utf-8")

    # Claim on its own is useful to non-Python consumers of domain evidence.
    claim_path = SCHEMA_DIR / "claim.schema.json"
    claim_path.write_text(
        json.dumps(contract_models.Claim.model_json_schema(), indent=2) + "\n", encoding="utf-8"
    )
    return path


def export_typescript() -> Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / "contracts.ts"
    path.write_text(generate_typescript(), encoding="utf-8")
    return path


def main() -> None:
    schema = export_schemas()
    types = export_typescript()
    print(f"schema     {schema.relative_to(REPO_ROOT)}  ({len(MODELS)} models, {len(ENUMS)} enums)")
    print(f"typescript {types.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
