"""Export the frozen contract to its three consumers.

    python -m packages.contracts.export

Writes:
  packages/contracts/schema.json      every model as JSON Schema
  ui/lib/contracts.ts                 TypeScript types, from the same models
  ui/lib/fixtures/*.json              a recorded case, so the cockpit runs with no backend

The point of doing all three from one place: `Claim` is simultaneously our Python
type, CALL-E's `recipient_result_schema` and the cockpit's TypeScript interface.
Generating them together means contract drift is not something anyone has to
remember to avoid -- it is structurally impossible.
"""

from __future__ import annotations

import json
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from pathlib import Path
from types import UnionType
from typing import Any, Union, get_args, get_origin

from pydantic import BaseModel

from packages.contracts import enums as contract_enums
from packages.contracts import models as contract_models
from packages.contracts.models import Contract

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = Path(__file__).resolve().parent
UI_LIB = REPO_ROOT / "ui" / "lib"

MODELS: dict[str, type[BaseModel]] = {
    name: obj
    for name, obj in vars(contract_models).items()
    if isinstance(obj, type)
    and issubclass(obj, BaseModel)
    and obj is not BaseModel
    and obj is not Contract
    and obj.__module__ == contract_models.__name__
}
# Enums live in two places now: Slice B's in enums.py, Slice C's (Channel,
# Currency) alongside Quote in models.py. Scan both so the generated TypeScript
# covers the whole contract.
ENUMS: dict[str, type[Enum]] = {
    name: obj
    for module in (contract_enums, contract_models)
    for name, obj in vars(module).items()
    if isinstance(obj, type)
    and issubclass(obj, Enum)
    and obj.__module__ == module.__name__
}


# ---------------------------------------------------------------------------
# TypeScript generation
# ---------------------------------------------------------------------------


def ts_type(annotation: Any) -> str:
    """Map a Python annotation to TypeScript.

    Money and dates deliberately become `string`: a Decimal serialized as a
    float in JSON is exactly the drift the money rule exists to prevent, so the
    wire format is a string and the UI formats it rather than doing arithmetic.
    """
    if annotation is Any:
        return "unknown"
    if annotation is type(None):
        return "null"
    # `Money` is Annotated[Decimal, ...]; unwrap to the type it decorates.
    if hasattr(annotation, "__metadata__"):
        return ts_type(annotation.__origin__)

    origin = get_origin(annotation)
    if origin in (Union, UnionType):
        parts = [ts_type(a) for a in get_args(annotation)]
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen)
    if origin in (list, set, tuple):
        args = get_args(annotation)
        return f"{ts_type(args[0])}[]" if args else "unknown[]"
    if origin is dict:
        args = get_args(annotation)
        key = "string" if not args else ("string" if args[0] in (str,) or (isinstance(args[0], type) and issubclass(args[0], Enum)) else "string")
        value = ts_type(args[1]) if len(args) > 1 else "unknown"
        return f"Record<{key}, {value}>"

    if isinstance(annotation, type):
        if issubclass(annotation, Enum):
            return annotation.__name__
        if issubclass(annotation, BaseModel):
            return annotation.__name__
        if annotation is Decimal:
            return "string"
        if annotation in (datetime, date):
            return "string"
        if annotation is bool:
            return "boolean"
        if annotation in (int, float):
            return "number"
        if annotation is str:
            return "string"
    return "unknown"


def generate_typescript() -> str:
    out: list[str] = [
        "// GENERATED by `python -m packages.contracts.export`. Do not edit by hand.",
        "//",
        "// These types come from the Pydantic models in packages/contracts/models.py,",
        "// which are also what CALL-E receives as `recipient_result_schema`. One source of",
        "// truth, three consumers.",
        "//",
        "// Money and dates are `string` on the wire on purpose -- a Decimal serialized as a",
        "// JSON float is exactly the drift we are avoiding. Format them, never sum them.",
        "",
    ]

    for name, enum_cls in sorted(ENUMS.items()):
        members = " | ".join(f'"{m.value}"' for m in enum_cls)
        out.append(f"export type {name} = {members}")
    out.append("")

    for name, model in sorted(MODELS.items()):
        doc = (model.__doc__ or "").strip().split("\n")[0]
        if doc:
            out.append(f"/** {doc} */")
        out.append(f"export interface {name} {{")
        for field_name, field in model.model_fields.items():
            optional = not field.is_required()
            rendered = ts_type(field.annotation)
            description = (field.description or "").strip()
            if description:
                out.append(f"  /** {description} */")
            out.append(f"  {field_name}{'?' if optional else ''}: {rendered}")
        out.append("}")
        out.append("")

    return "\n".join(out)


# ---------------------------------------------------------------------------


def export_schemas() -> Path:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    bundle = {name: model.model_json_schema() for name, model in sorted(MODELS.items())}
    path = SCHEMA_DIR / "schema.json"
    path.write_text(json.dumps(bundle, indent=2) + "\n", encoding="utf-8")

    # The one CALL-E needs, on its own, so Slice C can point at a single file.
    claim_path = SCHEMA_DIR / "claim.schema.json"
    claim_path.write_text(
        json.dumps(contract_models.Claim.model_json_schema(), indent=2) + "\n", encoding="utf-8"
    )
    return path


def export_typescript() -> Path:
    UI_LIB.mkdir(parents=True, exist_ok=True)
    path = UI_LIB / "contracts.ts"
    path.write_text(generate_typescript(), encoding="utf-8")
    return path


def export_fixtures() -> list[Path]:
    """A recorded case, not a mock.

    These come from the same endpoints the cockpit would call live, so the
    offline demo and the live one are the same code path with a different source.
    """
    from fastapi.testclient import TestClient

    from backend.api.main import app

    fixtures_dir = UI_LIB / "fixtures"
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    client = TestClient(app)

    written: list[Path] = []

    def dump(name: str, payload: Any) -> None:
        path = fixtures_dir / name
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        written.append(path)

    dump("shortages.json", client.get("/dashboard/shortages").json())
    dump("profile.json", client.get("/profile").json())
    dump("cases.json", client.get("/cases").json())

    for case_id in client.get("/cases").json():
        cid = case_id["case_id"]
        dump(f"{cid}.json", client.get(f"/cases/{cid}").json())
        dump(f"{cid}.events.json", client.get(f"/cases/{cid}/events").json())
        artifacts = client.get(f"/cases/{cid}/artifacts").json()["artifacts"]
        bodies = {
            a["name"]: client.get(f"/cases/{cid}/artifacts/{a['name']}").json()["body"]
            for a in artifacts
            if a["is_markdown"]
        }
        dump(f"{cid}.artifacts.json", bodies)

    return written


def main() -> None:
    schema = export_schemas()
    types = export_typescript()
    fixtures = export_fixtures()
    print(f"schema     {schema.relative_to(REPO_ROOT)}  ({len(MODELS)} models, {len(ENUMS)} enums)")
    print(f"typescript {types.relative_to(REPO_ROOT)}")
    for path in fixtures:
        print(f"fixture    {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
