import { CLAIMS } from "@/lib/case-001/claims"
import { SUPPLIER_RECORDS } from "@/lib/case-001/supplier-records"
import type { StockStatus, YesNoUnknown } from "@/lib/case-001/types"

export const CANDIDATES = [
  {
    id: "supplier-skf-nordic",
    name: "SKF Nordic",
    country: "SE",
    phone: "+46******0100",
    compliance: "passed" as const,
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[0],
    claim: CLAIMS[0],
    recordUnit: "EUR 4.20",
    recordLeadDays: "10",
    recordCertification: "IATF 16949",
    recordCertificationExpiresAt: "2026-11-30",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "40000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: "EUR 4.80",
    claimConfidence: "0.96",
    claimEvidence: "We can release 32,000 units from free stock.",
    claimLeadDays: "3",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "free_in_stock" as StockStatus,
    freight: "air",
  },
  {
    id: "supplier-schaeffler-fag",
    name: "Schaeffler FAG",
    country: "DE",
    phone: "+49*******0199",
    compliance: "passed" as const,
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[1],
    claim: CLAIMS[1],
    recordUnit: "EUR 2.40",
    recordLeadDays: "28",
    recordCertification: "IATF 16949",
    recordCertificationExpiresAt: "2027-03-31",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "50000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: "EUR 2.10",
    claimConfidence: "0.93",
    claimEvidence: "The full 32,000-unit batch must be made.",
    claimLeadDays: "21",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "to_be_made" as StockStatus,
    freight: "sea",
  },
  {
    id: "supplier-nsk-europe",
    name: "NSK Europe",
    country: "DE",
    phone: "+49*******0200",
    compliance: "passed" as const,
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[2],
    claim: CLAIMS[2],
    recordUnit: "EUR 3.10",
    recordLeadDays: "14",
    recordCertification: "IATF 16949",
    recordCertificationExpiresAt: "2026-08-15",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "32000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: "EUR 3.05",
    claimConfidence: "0.91",
    claimEvidence: "32,000 units are free for your order.",
    claimLeadDays: "14",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "free_in_stock" as StockStatus,
    freight: "road",
  },
  {
    id: "supplier-shenzhen-bearing",
    name: "Shenzhen Bearing Co",
    country: "CN",
    phone: "+86*******0100",
    compliance: "failed" as const,
    failedRules: ["blocked_origin_country"],
    supplierRecord: SUPPLIER_RECORDS[3],
    claim: null,
    recordUnit: "EUR 1.40",
    recordLeadDays: "35",
    recordCertification: "IATF 16949",
    recordCertificationExpiresAt: "2025-09-30",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "60000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: null,
    claimConfidence: null,
    claimEvidence: null,
    claimLeadDays: null,
    claimCertificationCurrent: null,
    stockStatus: null,
    freight: null,
  },
  {
    id: "supplier-munich-motion",
    name: "Munich Motion GmbH",
    country: "DE",
    phone: "+49*******0210",
    compliance: "passed" as const,
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[4],
    claim: CLAIMS[3],
    recordUnit: "EUR 3.80",
    recordLeadDays: "2",
    recordCertification: "IATF 16949",
    recordCertificationExpiresAt: "2026-05-20",
    recordKnownAllocations: "32000",
    recordMaxHistoricalFill: "32000",
    recordStockStatus: "in_stock_allocated" as StockStatus,
    claimUnit: "EUR 3.80",
    claimConfidence: "0.98",
    claimEvidence: "The units are allocated to another customer.",
    claimLeadDays: "2",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "in_stock_allocated" as StockStatus,
    freight: "road",
  },
] as const

export const FIELD_DIFF_ROWS = CANDIDATES.filter(
  (candidate) => candidate.claim !== null
).map((candidate) => ({
  candidateId: candidate.id,
  supplier: candidate.name,
  recordUnit: candidate.recordUnit,
  claimUnit: candidate.claimUnit,
  recordLeadDays: candidate.recordLeadDays,
  claimLeadDays: candidate.claimLeadDays,
  recordCertification: candidate.recordCertification,
  claimCertificationCurrent: candidate.claimCertificationCurrent,
  recordKnownAllocations: candidate.recordKnownAllocations,
  recordStockStatus: candidate.recordStockStatus,
  claimStockStatus: candidate.stockStatus,
  claimConfidence: candidate.claimConfidence,
  claimEvidence: candidate.claimEvidence,
}))
