import { CLAIMS } from "@/lib/case-001/claims"
import { SUPPLIER_RECORDS } from "@/lib/case-001/supplier-records"
import type {
  Candidate,
  StockStatus,
  YesNoUnknown,
} from "@/lib/case-001/types"

export const CANDIDATES: readonly Candidate[] = [
  {
    id: "supplier-kby",
    supplierRef: "SUP-KBY",
    name: "Kugellager Bayern GmbH",
    country: "DE",
    phone: "+49*******0142",
    compliance: "passed" as const,
    researchChannel: "voice" as const,
    researchAfterId: "claims",
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[0],
    claim: CLAIMS[0],
    recordUnit: "EUR 1.42",
    recordLeadDays: "10",
    recordCertification: "ISO 9001 · DIN 625",
    recordCertificationExpiresAt: "2027-05-31",
    recordKnownAllocations: "18000",
    recordMaxHistoricalFill: "30000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: "EUR 1.49",
    claimConfidence: "0.73",
    claimEvidence: "We can release 12,000 pcs from free stock in 12 days.",
    claimLeadDays: "12",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "free_in_stock" as StockStatus,
    freight: "road",
  },
  {
    id: "supplier-npb",
    supplierRef: "SUP-NPB",
    name: "Ningbo Precision Bearing Co. Ltd",
    country: "CN",
    phone: "+49*******0188",
    compliance: "failed" as const,
    researchChannel: "none" as const,
    researchAfterId: "policy",
    failedRules: ["blocked_origin_country"],
    supplierRecord: SUPPLIER_RECORDS[1],
    claim: null,
    recordUnit: "EUR 0.92",
    recordLeadDays: "34",
    recordCertification: "ISO 9001 · DIN 625",
    recordCertificationExpiresAt: "2027-09-30",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "0",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: null,
    claimConfidence: null,
    claimEvidence: null,
    claimLeadDays: null,
    claimCertificationCurrent: null,
    stockStatus: null,
    freight: null,
  },
  {
    id: "supplier-pul",
    supplierRef: "SUP-PUL",
    name: "Pulman AG",
    country: "DE",
    phone: "+49*******0174",
    compliance: "failed" as const,
    researchChannel: "none" as const,
    researchAfterId: "policy",
    failedRules: ["missing_required_certification"],
    supplierRecord: SUPPLIER_RECORDS[2],
    claim: null,
    recordUnit: "EUR 1.15",
    recordLeadDays: "16",
    recordCertification: "DIN 625 lapsed 2026-03-31",
    recordCertificationExpiresAt: "2026-03-31",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "12000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: null,
    claimConfidence: null,
    claimEvidence: null,
    claimLeadDays: null,
    claimCertificationCurrent: null,
    stockStatus: null,
    freight: null,
  },
  {
    id: "supplier-rul",
    supplierRef: "SUP-RUL",
    name: "Rulmenti Est SRL",
    country: "RO",
    phone: "+49*******0163",
    compliance: "passed" as const,
    researchChannel: "voice" as const,
    researchAfterId: "claims",
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[3],
    claim: CLAIMS[1],
    recordUnit: "EUR 1.30",
    recordLeadDays: "21",
    recordCertification: "ISO 9001 · DIN 625",
    recordCertificationExpiresAt: "2027-02-28",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "45000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: "EUR 1.31",
    claimConfidence: "0.87",
    claimEvidence: "The full 36,000-pc batch can be made in 24 days.",
    claimLeadDays: "24",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "to_be_made" as StockStatus,
    freight: "road",
  },
  {
    id: "supplier-nbt",
    supplierRef: "SUP-NBT",
    name: "NordBearing Trading ApS",
    country: "DK",
    phone: "+49*******0151",
    compliance: "failed" as const,
    researchChannel: "none" as const,
    researchAfterId: "policy",
    failedRules: ["audit_required_and_not_audited"],
    supplierRecord: SUPPLIER_RECORDS[4],
    claim: null,
    recordUnit: "EUR 1.35",
    recordLeadDays: "8",
    recordCertification: "ISO 9001 · DIN 625",
    recordCertificationExpiresAt: "2028-01-31",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "0",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: null,
    claimConfidence: null,
    claimEvidence: null,
    claimLeadDays: null,
    claimCertificationCurrent: null,
    stockStatus: null,
    freight: null,
  },
  {
    id: "supplier-skf",
    supplierRef: "SUP-SKF",
    name: "SKF Deutschland Vertrieb GmbH",
    country: "DE",
    phone: "+49*******0117",
    compliance: "passed" as const,
    researchChannel: "voice" as const,
    researchAfterId: "claims",
    failedRules: [] as string[],
    supplierRecord: SUPPLIER_RECORDS[5],
    claim: CLAIMS[2],
    recordUnit: "EUR 1.95",
    recordLeadDays: "6",
    recordCertification: "ISO 9001 · DIN 625",
    recordCertificationExpiresAt: "2027-11-30",
    recordKnownAllocations: "0",
    recordMaxHistoricalFill: "8000",
    recordStockStatus: "unclear" as StockStatus,
    claimUnit: "EUR 2.19",
    claimConfidence: "0.85",
    claimEvidence: "8,000 pcs of free stock can ship in 6 days.",
    claimLeadDays: "6",
    claimCertificationCurrent: "yes" as YesNoUnknown,
    stockStatus: "free_in_stock" as StockStatus,
    freight: "road",
  },
]

export const FIELD_DIFF_ROWS = CANDIDATES.filter(
  (candidate) => candidate.claim !== null
).map((candidate) => ({
  candidateId: candidate.id,
  supplier: candidate.name,
  recordUnit: candidate.recordUnit,
  claimUnit: candidate.claimUnit,
  recordLeadDays: candidate.recordLeadDays,
  claimLeadDays: candidate.claimLeadDays,
  recordCertification: candidate.recordCertification,
  claimCertificationCurrent: candidate.claimCertificationCurrent,
  recordKnownAllocations: candidate.recordKnownAllocations,
  recordStockStatus: candidate.recordStockStatus,
  claimStockStatus: candidate.stockStatus,
  claimConfidence: candidate.claimConfidence,
  claimEvidence: candidate.claimEvidence,
}))
