import type { Claim } from "@/lib/case-001/types"

export const CLAIMS = [
  {
    supplierId: "supplier-skf-nordic",
    round: 1,
    sourceChannel: "voice",
    sourceRef: "call:skf",
    callId: "skf",
    quantityAvailable: "32000",
    earliestReady: "3 days",
    priceQuoted: "yes",
    unitPrice: "EUR 4.80",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "free_in_stock",
    confidence: "0.96",
    evidence: [
      "We can release 32,000 units from free stock.",
      "The IATF 16949 certificate is current.",
    ],
  },
  {
    supplierId: "supplier-schaeffler-fag",
    round: 1,
    sourceChannel: "voice",
    sourceRef: "call:fag",
    callId: "fag",
    quantityAvailable: "32000",
    earliestReady: "21 days",
    priceQuoted: "yes",
    unitPrice: "EUR 2.10",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "to_be_made",
    confidence: "0.93",
    evidence: [
      "The full 32,000-unit batch must be made.",
      "Production can be ready in 21 days.",
    ],
  },
  {
    supplierId: "supplier-nsk-europe",
    round: 1,
    sourceChannel: "website",
    sourceRef: "fixture-web:nsk-europe/6204-2RS",
    quantityAvailable: "32000",
    earliestReady: "14 days",
    priceQuoted: "yes",
    unitPrice: "EUR 3.05",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "free_in_stock",
    confidence: "0.91",
    evidence: [
      "32,000 units are free for your order.",
      "Road delivery is available after 14 days.",
    ],
  },
  {
    supplierId: "supplier-munich-motion",
    round: 1,
    sourceChannel: "voice",
    sourceRef: "call:munich-motion",
    callId: "munich-motion",
    quantityAvailable: "32000",
    earliestReady: "2 days",
    priceQuoted: "yes",
    unitPrice: "EUR 3.80",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "in_stock_allocated",
    confidence: "0.98",
    evidence: [
      "The units are allocated to another customer.",
      "I cannot promise those units to you.",
    ],
  },
] as const satisfies readonly Claim[]
