import type { Claim } from "@/lib/case-001/types"

export const CLAIMS: readonly Claim[] = [
  {
    supplierId: "supplier-kby",
    round: 1,
    sourceChannel: "voice",
    sourceRef: "call:kby",
    callId: "kby",
    quantityAvailable: "12000",
    earliestReady: "12 days",
    priceQuoted: "yes",
    unitPrice: "EUR 1.49",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "free_in_stock",
    confidence: "0.73",
    evidence: [
      "Confirmed 6204-2RS; we can ship 12,000 pcs in 12 days.",
      "ISO 9001 and DIN 625 conformity are current.",
    ],
  },
  {
    supplierId: "supplier-rul",
    round: 1,
    sourceChannel: "voice",
    sourceRef: "call:rul",
    callId: "rul",
    quantityAvailable: "36000",
    earliestReady: "24 days",
    priceQuoted: "yes",
    unitPrice: "EUR 1.31",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "to_be_made",
    confidence: "0.87",
    evidence: [
      "Confirmed 6204-2RS; we can ship the full 36,000 pcs in 24 days.",
      "The batch has to be produced; nothing is on the shelf today.",
    ],
  },
  {
    supplierId: "supplier-skf",
    round: 1,
    sourceChannel: "voice",
    sourceRef: "call:skf",
    callId: "skf",
    quantityAvailable: "8000",
    earliestReady: "6 days",
    priceQuoted: "yes",
    unitPrice: "EUR 2.19",
    currency: "EUR",
    certificationCurrent: "yes",
    partNumberConfirmed: "yes",
    stockStatus: "free_in_stock",
    confidence: "0.85",
    evidence: [
      "Confirmed 6204-2RS; 8,000 pcs can leave the warehouse in 6 days.",
      "That is the whole free stock we hold for this bearing.",
    ],
  },
]
