import type { OutreachTaskStatus } from "@/lib/case-001/types"

export const OUTREACH_TASKS = [
  {
    id: "outreach-case-001-skf",
    caseId: "CASE-001",
    candidateId: "supplier-skf-nordic",
    channel: "phone",
    maskedPhone: "+46******0100",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2025-02-14T09:15:00Z",
    callId: "skf",
  },
  {
    id: "outreach-case-001-fag",
    caseId: "CASE-001",
    candidateId: "supplier-schaeffler-fag",
    channel: "phone",
    maskedPhone: "+49*******0199",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2025-02-14T09:15:00Z",
    callId: "fag",
  },
  {
    id: "outreach-case-001-nsk",
    caseId: "CASE-001",
    candidateId: "supplier-nsk-europe",
    channel: "phone",
    maskedPhone: "+49*******0200",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2025-02-14T09:15:00Z",
    callId: "nsk",
  },
  {
    id: "outreach-case-001-munich-motion",
    caseId: "CASE-001",
    candidateId: "supplier-munich-motion",
    channel: "phone",
    maskedPhone: "+49*******0210",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2025-02-14T09:15:00Z",
    callId: "munich-motion",
  },
] as const
