import type { OutreachTaskStatus } from "@/lib/case-001/types"

export const OUTREACH_TASKS = [
  {
    id: "outreach-case-001-kby",
    caseId: "CASE-001",
    candidateId: "supplier-kby",
    channel: "phone",
    maskedPhone: "+49*******0142",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2026-08-22T09:15:00Z",
    callId: "kby",
  },
  {
    id: "outreach-case-001-rul",
    caseId: "CASE-001",
    candidateId: "supplier-rul",
    channel: "phone",
    maskedPhone: "+49*******0163",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2026-08-22T09:15:00Z",
    callId: "rul",
  },
  {
    id: "outreach-case-001-skf",
    caseId: "CASE-001",
    candidateId: "supplier-skf",
    channel: "phone",
    maskedPhone: "+49*******0117",
    status: "completed" as OutreachTaskStatus,
    batchId: "case-001-round-1",
    round: 1,
    startedAt: "2026-08-22T09:15:00Z",
    callId: "skf",
  },
] as const
