export const SUPPLIER_RECORDS = [
  {
    supplierId: "supplier-kby",
    supplierRef: "SUP-KBY",
    displayName: "Kugellager Bayern GmbH",
    maskedPhone: "+49*******0142",
    countryRegion: "DE",
    language: "de",
    partId: "6204-2RS",
    approved: true,
    preferred: true,
    contractUnitPrice: "EUR 1.42",
    standardLeadDays: "10",
    certification: "ISO 9001 · DIN 625",
    certificationExpiresAt: "2027-05-31",
    knownAllocations: "18000",
    maxHistoricalFill: "30000",
  },
  {
    supplierId: "supplier-npb",
    supplierRef: "SUP-NPB",
    displayName: "Ningbo Precision Bearing Co. Ltd",
    maskedPhone: "+49*******0188",
    countryRegion: "CN",
    language: "en",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 0.92",
    standardLeadDays: "34",
    certification: "ISO 9001 · DIN 625",
    certificationExpiresAt: "2027-09-30",
    knownAllocations: "0",
    maxHistoricalFill: "0",
  },
  {
    supplierId: "supplier-pul",
    supplierRef: "SUP-PUL",
    displayName: "Pulman AG",
    maskedPhone: "+49*******0174",
    countryRegion: "DE",
    language: "en",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 1.15",
    standardLeadDays: "16",
    certification: "ISO 9001 · DIN 625",
    certificationExpiresAt: "2026-03-31",
    knownAllocations: "0",
    maxHistoricalFill: "12000",
  },
  {
    supplierId: "supplier-rul",
    supplierRef: "SUP-RUL",
    displayName: "Rulmenti Est SRL",
    maskedPhone: "+49*******0163",
    countryRegion: "RO",
    language: "en",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 1.30",
    standardLeadDays: "21",
    certification: "ISO 9001 · DIN 625",
    certificationExpiresAt: "2027-02-28",
    knownAllocations: "0",
    maxHistoricalFill: "45000",
  },
  {
    supplierId: "supplier-nbt",
    supplierRef: "SUP-NBT",
    displayName: "NordBearing Trading ApS",
    maskedPhone: "+49*******0151",
    countryRegion: "DK",
    language: "en",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 1.35",
    standardLeadDays: "8",
    certification: "ISO 9001 · DIN 625",
    certificationExpiresAt: "2028-01-31",
    knownAllocations: "0",
    maxHistoricalFill: "0",
  },
  {
    supplierId: "supplier-skf",
    supplierRef: "SUP-SKF",
    displayName: "SKF Deutschland Vertrieb GmbH",
    maskedPhone: "+49*******0117",
    countryRegion: "DE",
    language: "de",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 1.95",
    standardLeadDays: "6",
    certification: "ISO 9001 · DIN 625",
    certificationExpiresAt: "2027-11-30",
    knownAllocations: "0",
    maxHistoricalFill: "8000",
  },
] as const
