export const SUPPLIER_RECORDS = [
  {
    supplierId: "supplier-skf-nordic",
    displayName: "SKF Nordic",
    maskedPhone: "+46******0100",
    countryRegion: "SE",
    language: "en",
    partId: "6204-2RS",
    approved: true,
    preferred: true,
    contractUnitPrice: "EUR 4.20",
    standardLeadDays: "10",
    certification: "IATF 16949",
    certificationExpiresAt: "2026-11-30",
    knownAllocations: "0",
    maxHistoricalFill: "40000",
  },
  {
    supplierId: "supplier-schaeffler-fag",
    displayName: "Schaeffler FAG",
    maskedPhone: "+49*******0199",
    countryRegion: "DE",
    language: "de",
    partId: "6204-2RS",
    approved: true,
    preferred: true,
    contractUnitPrice: "EUR 2.40",
    standardLeadDays: "28",
    certification: "IATF 16949",
    certificationExpiresAt: "2027-03-31",
    knownAllocations: "0",
    maxHistoricalFill: "50000",
  },
  {
    supplierId: "supplier-nsk-europe",
    displayName: "NSK Europe",
    maskedPhone: "+49*******0200",
    countryRegion: "DE",
    language: "de",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 3.10",
    standardLeadDays: "14",
    certification: "IATF 16949",
    certificationExpiresAt: "2026-08-15",
    knownAllocations: "0",
    maxHistoricalFill: "32000",
  },
  {
    supplierId: "supplier-shenzhen-bearing",
    displayName: "Shenzhen Bearing Co",
    maskedPhone: "+86*******0100",
    countryRegion: "CN",
    language: "en",
    partId: "6204-2RS",
    approved: false,
    preferred: false,
    contractUnitPrice: "EUR 1.40",
    standardLeadDays: "35",
    certification: "IATF 16949",
    certificationExpiresAt: "2025-09-30",
    knownAllocations: "0",
    maxHistoricalFill: "60000",
  },
  {
    supplierId: "supplier-munich-motion",
    displayName: "Munich Motion GmbH",
    maskedPhone: "+49*******0210",
    countryRegion: "DE",
    language: "de",
    partId: "6204-2RS",
    approved: true,
    preferred: false,
    contractUnitPrice: "EUR 3.80",
    standardLeadDays: "2",
    certification: "IATF 16949",
    certificationExpiresAt: "2026-05-20",
    knownAllocations: "32000",
    maxHistoricalFill: "32000",
  },
] as const
